# app set
resources:
  - ../apps/transport-broker

# upstream set
configMapGenerator:
  - name: ext-service
    envs:
      - ../upstreams/ext-service/dev.env

# cross-cutting fields
namespace: uat2
namePrefix: uat2-
commonLabels:
  env: uat2

# processes API endpoints
replacements:
  - source:
      kind: StatefulSet
      name: transport-broker
    targets:
      - select:
          kind: ConfigMap
          name: transport-broker
        fieldPaths:
          - data.TRANSPORT_BROKER_SVC_NAME

# versions
images:
  - name: example.com/transport-broker
    newTag: v0.1-uat2
