resources:
  - ../../../apps/cache-server

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cache-server
    spec:
      template:
        spec:
          containers:
            - name: cache-server
              env:
                - name: SPRING_PROFILE_ACTIVE
                  value: uat
