apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transport-broker
spec:
  serviceName: transport-broker
  selector:
    matchLabels:
      app: transport-broker
  template:
    metadata:
      labels:
        app: transport-broker
    spec:
      containers:
        - name: transport-broker
          image: gcr.io/google-containers/busybox
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
