apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
spec:
  selector:
    matchLabels:
      app: cache-server
  template:
    metadata:
      labels:
        app: cache-server
    spec:
      containers:
        - name: cache-server
          image: gcr.io/google-containers/busybox
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE_ACTIVE
              value: dev,mocked
          envFrom:
            - configMapRef:
                name: transport-broker
