apiVersion: v1
kind: Service
metadata:
  name: transport-broker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: transport-broker
  ports:
    - name: ws
      port: 8080
      targetPort: 8080
