apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transport-broker
spec:
  serviceName: transport-broker
  selector:
    matchLabels:
      app: transport-broker
  template:
    metadata:
      labels:
        app: transport-broker
    spec:
      containers:
        - name: transport-broker
          image: example.com/transport-broker
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          ports:
            - name: ws
              containerPort: 8080
          env:
            - name: COMPONENT
              value: transport-broker
            - name: SPRING_PROFILE_ACTIVE
              value: dev,mocked
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: ext-service
