apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: svc-name-replacements
replacements:
  - source:
      kind: StatefulSet
    targets:
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint0
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint0
        options:
          delimiter: "."
          index: 1
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint1
        options:
          delimiter: "-"
          index: 0
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint1
        options:
          delimiter: "."
          index: 1
  - source:
      kind: StatefulSet
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint0
        options:
          delimiter: "."
          index: 2
      - select:
          kind: ConfigMap
        fieldPaths:
          - data.endpoint1
        options:
          delimiter: "."
          index: 2
